### ISSUE TITLE
Cannot download from the Store

### ISSUE THREAD

**Issue by MarcAnt01** [Sylvain2703/MessengerUWP#7]
**Describe the bug**
An error appears when I try to download the app from the Store

**To Reproduce**
Just go to MS Store

**Expected behavior**
Download the app

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/83612220-678f5680-a582-11ea-8709-cfec521eb842.png)

**Device and Application Information**
 - Facebook Messenger Version: cannot see it
 - Device Family: Laptop
 - Device Model: Surface Book 2
 - OS Build: Windows 10 2004
 - Architecture: x64
 - Application Version: cannot see it
 - Region: Italy

**Additional context**
_Add any other context about the problem here._

**Comment by Sylvain2703** [comment]
Hello,

Thank you for opening this issue.

Are you well using the same email address in the Microsoft Store as the one you entered in the Google Forms?
As the app is in private preview, the Microsoft Store checks using the email address if you are authorized to download the app.

**Comment by MarcAnt01** [comment]
Yes, I only have one e-mail account that's the same I use in Microsoft Store

**Comment by Sylvain2703** [comment]
Ok, so I don't understand why you are not able to download the app.
Are you able to install other apps from the Store today?

**Comment by MarcAnt01** [comment]
Yes, no problem with the other apps

**Comment by Sylvain2703** [comment]
This is really strange. You are the first one who has this issue.

As a temporary workaround, you can download the app from the [Release tab in GitHub](https://github.com/Sylvain2703/MessengerUWP/releases). Open the **Assets** section of the latest release and download `MessengerUWP_X.Y.Z.zip`.
The zip contains APPX files for each architecture (under "AppPackages\Messenger UWP_*X.Y.Z.0*_*Architecture*_Test")

**Comment by MarcAnt01** [comment]
OK, I tried now and everything is all right, probably something Store-side
